@Projects
Feature: Projects in Clockify

  Background:
    Given base url https://api.clockify.me/api
    And header Content-Type = application/json
    And header Accept = */*

  @AddNewProject
  Scenario: Add a new project.
    And endpoint /v1/workspaces/680ab99aaf0c792d89b73fa7/projects
    And header x-api-key = NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz
    And body jsons/bodies/bodyAddProject.json
    When execute method POST
    Then the status code should be 201
    And response should be name = Proyecto BAT
    And validate schema jsons/schemas/addProject.json
    * define projectId = $.id

  @FindProjectById
  Scenario: Find project by ID.
    And header x-api-key = NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz
    And endpoint /v1/workspaces/680ab99aaf0c792d89b73fa7/projects/681949a23e62a459a1c6ea96
    When execute method GET
    Then the status code should be 200
    And response should be name = reportes de errores
    * print response

  @UpdateProject
  Scenario: Update project on workspace
    Given call ClockifyProject.feature@AddNewProject
    And header x-api-key = NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz
    And endpoint /v1/workspaces/680ab99aaf0c792d89b73fa7/projects/{{projectId}}
    And body jsons/bodies/bodyUpdateProject.json
    When execute method PUT
    Then the status code should be 200
    And response should be name = Proyecto archivado

  @DeleteProject
  Scenario: Delete project from workspace
    Given call ClockifyProject.feature@UpdateProject
    And header x-api-key = NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz
    And endpoint /v1/workspaces/680ab99aaf0c792d89b73fa7/projects/{{projectId}}
    When execute method DELETE
    Then the status code should be 200

  @FallaAddNewProject
  Scenario Outline: crack Add new project for <reason>
    And endpoint /v1/workspaces/<workspaceId>/projects
    And header x-api-key = <api-key>
    * define body = jsons/bodies/bodyAddProject.json
    And set value <name> of key name in body $(body)
    And body <body>
    When execute method POST
    Then the status code should be <status-code>
    Examples:
      | reason                                     | workspaceId              | api-key                                          | name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | body    | status-code |
      | empty workspaceId                          |                          | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 403         |
      | null workspaceId                           | null                     | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 403         |
      | incomplete workspaceId                     | 680ab99aaf0c792d89b73    | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 403         |
#      en este caso uso un workspaceId existente, y una api-key existente pero de un usuario que no tiene permisos
      | api-key without permissions                | 680ab99aaf0c792d89b73fa7 | MzdjNDZlM2YtYTM4ZS00NmU3LThjNmUtNmQ4YWJiZTg5NDhl | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 403         |
      | no body in request                         | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |         | 400         |
      | empty project name                         | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | ""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | $(body) | 400         |
      #va a fallar porque hay un bug, se puede crear nombre del proyecto con la palabra null
      | null project name                          | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 400         |
      | project name with one character            | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | "T"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | $(body) | 400         |
      | project name with more than 250 characters | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | "diluir a 1:100.000 = 0.01 mg/ml (0.1 ml más 10 ml de SF).Administrar en 5-10 minutos.Pacientes en tratamiento con inhibidores de la monoaminooxidasa (bloquean el metabolismo de la adrenalina), antidepresivos tricíclicos (prolongan la vida media de la adrenalina), bloqueantes beta (respuesta parcial de la adrenalina), aminofilina, salbutamol IV u otros fármacos vasoconstrictoresdiluir a 1:100.000 = 0.01 mg/ml (0.1 ml más 10 ml de SF).Administrar en 5-10 minutos.Pacientes en tratamiento con inhibidores de la monoaminooxidasa (bloquean el metabolismo de la adrenalina), antidepresivos tricíclicos (prolongan la vida media de la adrenalina), bloqueantes beta (respuesta parcial de la adrenalina), aminofilina, salbutamol IV u otros fármacos vasoconstrictoresdiluir a 1:100.000 = 0.01 mg/ml (0.1 ml más 10 ml de SF).Administrar en 5-10 minutos.Pacientes en tratamiento con inhibidores de la monoaminooxidasa (bloquean el metabolismo de la adrenalina), antidepresivos tricíclicos (prolongan la vida media de la adrenalina), bloqueantes beta (respuesta parcial de la adrenalina), aminofilina, salbutamol IV u otros fármacos vasoconstrictoresdiluir a 1:100.000 = 0.01 mg/ml (0.1 ml más 10 ml de SF).Administrar en 5-10 minutos.Pacientes en tratamiento con inhibidores de la monoaminooxidasa (bloquean el metabolismo de la adrenalina), antidepresivos tricíclicos (prolongan la vida media de la adrenalina), bloqueantes beta (respuesta parcial de la adrenalina), aminofilina, salbutamol IV u otros fármacos vasoconstrictoresdiluir a 1:100.000 = 0.01 mg/ml (0.1 ml más 10 ml de SF).Administrar en 5-10 minutos.Pacientes en tratamiento con inhibidores de la monoaminooxidasa (bloquean el metabolismo de la adrenalina), antidepresivos tricíclicos (prolongan la vida media de la adrenalina), bloqueantes beta (respuesta parcial de la adrenalina), aminofilina, salbutamol IV u otros fármacos vasoconstrictoresyunosmascaracteres" | $(body) | 400         |
      | empty api-key                              | 680ab99aaf0c792d89b73fa7 |                                                  | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 401         |
      | null api-key                               | 680ab99aaf0c792d89b73fa7 | null                                             | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 401         |
      | non-existent api-key                       | 680ab99aaf0c792d89b73fa7 | 515156sgsafaiu9esf84s48ddsg                      | "Proyecto BAT error"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | $(body) | 401         |


  @FallaFindProjectById
  Scenario Outline: crack Find project by ID for <reason>.
    And header x-api-key = <api-key>
    And endpoint /v1/workspaces/<workspaceId>/projects/<projectId>
    When execute method GET
    Then the status code should be <status-code>
    #hay que validar mensaje del json!!!!!!!!!1

    Examples:
      | reason                      | workspaceId              | api-key                                          | projectId                | status-code |
      | empty workspaceId           |                          | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | 681949a23e62a459a1c6ea96 | 404         |
      | null workspaceId            | null                     | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | 681949a23e62a459a1c6ea96 | 403         |
      | incomplete workspaceId      | 680ab99aaf0c792d89b73    | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | 681949a23e62a459a1c6ea96 | 403         |
      | api-key without permissions | 680ab99aaf0c792d89b73fa7 | MGE5ZTA2NzgtOGYzMi00ZjQzLWE2ZTEtNjBhOGYyYjhiMTJm | 681949a23e62a459a1c6ea96 | 403         |
      | empty api-key               | 680ab99aaf0c792d89b73fa7 |                                                  | 681949a23e62a459a1c6ea96 | 401         |
      | null api-key                | 680ab99aaf0c792d89b73fa7 | null                                             | 681949a23e62a459a1c6ea96 | 401         |
      | non-existent api-key        | 680ab99aaf0c792d89b73fa7 | 515156sgsafaiu9esf84s48ddsg                      | 681949a23e62a459a1c6ea96 | 401         |
      | empty projectId             | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz |            {}            | 400         |
      | null projectId              | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | null                     | 400         |
      | non-existent projectId      | 680ab99aaf0c792d89b73fa7 | NjliOWFiYmUtMzc2ZC00Zjg2LWJhYzUtNWIzOTE1ZjlkYmIz | 681949a23e62a459a1fr5e   | 400         |




  
